project:
  type: website
  render:
    - index.qmd
    - projects/*.qmd

website:
  site-url: https://root-project.github.io/open_projects/
  title: >-
    <img src="assets/images/root_logo_cyan.png" alt="" style="height:35px; vertical-align:middle;">
  description: Opportunities for collaboration and contributions with the ROOT Core Team
  repo-url: 'https://github.com/root-project/open_projects'
  navbar:
    brand:
      image: assets/images/root_logo_cyan.png
      text: ROOT Open Projects
      href: index.html
    type: default
    right:
      - text: Home
        href: index.html
      - text: Projects
        href: 'index.html#projects'
      - icon: github
        href: 'https://github.com/root-project/root'
      - icon: envelope
        href: 'mailto:root-dev@cern.ch'

format:
  html:
    theme: cosmo
    css: css/style.css
    toc: false
    smooth-scroll: true
    embed-resources: true